### ISSUE TITLE
WMT slower in Pytorch than Jax

### ISSUE THREAD

**Issue by priyakasimbeg** [mlcommons/algorithmic-efficiency#467] opened 2023-08-08 18:17 UTC
WMT pytorch is currently slower than Jax.

This bug is intended to at least document possible causes. 

@runame @pomonam could you please summarize current findings and possible solutions?

**Comment by msaroufim** [comment] 2023-08-11 16:08
FWIW I did try using the HF implementation with boolean masks and that `torch.compile`'d just fine https://gist.github.com/msaroufim/946d7d26e89bab0bfe83d9929b533701

**Comment by msaroufim** [comment] 2023-08-12 01:48
@runame I managed to `torch.compile()` the wmt model just now an A10G using pytorch nightlies

`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118 --force-reinstall`

I don't have perf numbers yet since it feels stuck at `Translating evaluation dataset` - do you mind trying it out on your end as well and lmk if you hit any new errors?

**Comment by pomonam** [comment] 2023-08-12 01:50
@msaroufim Thank you so much for looking into this! Yes, I will try this and see if there are any new issues.

**Comment by runame** [comment] 2023-08-12 09:59
@msaroufim @pomonam Thanks a lot for investigating! I won't get to working on this before Sunday or Monday, will check this thread for updates then.

**Comment by pomonam** [comment] 2023-08-14 20:59
@runame One thing I wanted to try out (but did not have time to do) was to use the PyTorch default functions (e.g., `multi_head_attention_forward`) when don't need cache - training. I am not sure how useful this might be, but I think it is worth a try. Also, with `torch.compile`, the graph seems to break many times (and the timings don't change much), but I am not sure how to fix this.

**Comment by msaroufim** [comment] 2023-08-14 23:47
Oh interesting so you can confirm that it does compile but you're getting graph breaks? Are you running `fullgraph=True`? 

Also could you print the logs you're getting

**Comment by runame** [comment] 2023-08-23 14:54
Branch `dev` (also with changes from #489, also with `torch.compile` before `DDP`) + stable + `fullgraph=True`:

```
Traceback (most recent call last):
  File "submission_runner.py", line 624, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "submission_runner.py", line 595, in main
    score = score_submission_on_workload(
  File "submission_runner.py", line 520, in score_submission_on_workload
    timing, metrics = train_once(workload, global_batch_size,
  File "submission_runner.py", line 299, in train_once
    optimizer_state, model_params, model_state = update_params(
  File "/algorithmic-efficiency/baselines/adamw/pytorch/submission.py", line 74, in update_params
    logits_batch, new_model_state = workload.model_fn(
  File "/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/workload.py", line 212, in model_fn
    logits_batch = model(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/algorithmic-efficiency/algorithmic_efficiency/workloads/wmt/wmt_pytorch/models.py", line 178, in forward
    memory = self.encoder(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/eval_frame.py", line 334, in catch_errors
    return hijacked_callback(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/symbolic_convert.py", line 372, in wrapper
    self.output.compile_subgraph(self, reason=reason)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 541, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: compile_fn raised TypeError: _convert_frame_assert() missing 1 required positional argument: 'hooks'
```

**Comment by msaroufim** [comment] 2023-08-23 20:16
Well it is promising that `torch.compile()` with inductor works - if the failure is only with `fullgraph=True` try out `torch.compile(m, backend="explain")` which should help debug

If I could get access to your VM to run experiments quickly that might help as well @priyakasimbeg

**Comment by runame** [comment] 2023-08-24 17:22
@msaroufim Is the `'explain'` backend supposed to be available with the current nightly (2.1.0.dev20230824+cu118)? I get an error and `torch._dynamo.list_backends()` only lists `['cudagraphs', 'inductor', 'onnxrt', 'tvm']`.

**Comment by msaroufim** [comment] 2023-08-24 18:06
Hmm it should also be usable by `torch._dynamo.explain()` it should litst out all the reasons for graph breaks

**Comment by runame** [comment] 2023-08-29 15:19
@msaroufim After the refactor in #489 the only remaining graph breaks are of this type:
```
Reason: DDPOptimizer intentional graph-break (See Note [DDPOptimizer]).
```
After setting `torch._dynamo.config.optimize_ddp = False` there are no graph breaks left and I'm still getting [this error](https://github.com/mlcommons/algorithmic-efficiency/issues/487#issuecomment-1679732542).

**Comment by msaroufim** [comment] 2023-08-30 18:05
@runame I chatted with Will Constable about this and his point is the DDPOptimizer will always give you graph breaks so if you have it enabled you won't be able to do `fullgraph=True` either

Do either you or @pomonam have a smaller repro of the linked error here https://github.com/mlcommons/algorithmic-efficiency/issues/487#issuecomment-1679732542

**Comment by runame** [comment] 2023-08-31 15:11
Not sure if it's useful, but I have created a smaller repro using the same model [here](https://github.com/runame/algorithmic-efficiency/blob/wmt-debugging/tests/test_wmt_compile.py). It runs successfully on a single GPU and fails with DDP.

**Comment by runame** [comment] 2023-09-06 14:48
@msaroufim Since we don't know why we get basically no speed improvements from using `torch.compile` despite using a standard transformer architecture and having no graph breaks, I have two other questions:

1. Could you take a look at the [model code](https://github.com/runame/algorithmic-efficiency/blob/wmt-speed/algorithmic_efficiency/workloads/wmt/wmt_pytorch/models.py) (from PR #489) and check if there are any obvious inefficiencies? I think the only non-standard part is the creation of the masks, but I have already timed a run without them to exclude them as the bottleneck and they seem to make almost no difference to the runtime.
2. Maybe we misattributed the slow-down to the forward and backward pass due to a bug in our timing code and it is actually caused by something else, e.g. the data loading. You can find the code of the profiler that we use to time the different parts of training [here](https://github.com/runame/algorithmic-efficiency/blob/wmt-speed/algorithmic_efficiency/profiler.py). Essentially, we use `torch.cuda.synchronize()` together with `time.time()` or `time.monotonic()` for timing.

**Comment by wconstab** [comment] 2023-09-12 17:50
> torch._dynamo.exc.BackendCompilerFailed: compile_fn raised TypeError: _convert_frame_assert() missing 1 required positional argument: 'hooks'

@runame @msaroufim Not sure if this is relevant anymore (if you're unblocked some other way) but this specific issue about 'hooks' from the DDPOptimizer should have been fixed on master by https://github.com/pytorch/pytorch/pull/107834.

**Comment by priyakasimbeg** [comment] 2023-12-13 23:55
Resolved in  https://github.com/mlcommons/algorithmic-efficiency/pull/597 after torch.compiling the loss functions.

**Closed** 2023-12-13 23:54 UTC
Labels: ⏰ Timing gap
