### ISSUE TITLE
Drop remainder batch during training and keep it for evaluation

### ISSUE THREAD

**Issue by runame** [mlcommons/algorithmic-efficiency#54] opened 2022-01-28 09:35 UTC
Since the training data is reshuffled after each epoch, it is fine to drop the last partial batch during training, to ensure the same batch size for all batches. In contrast, to see the whole evaluation data set, we need to keep the last partial batch during evaluation.

The ImageNet PyTorch workload already implements this, but the other workloads need to be checked and adjusted to adhere to the same behavior.

**Comment by znado** [comment] 2022-10-08 16:36
All of the `tf.data` workloads should [already do this](https://github.com/mlcommons/algorithmic-efficiency/search?q=drop_remainder), so I think this is mostly an issue for evals, so I'm going to mark it as a duplicate of https://github.com/mlcommons/algorithmic-efficiency/issues/119

**Closed by znado** 2022-10-08 16:36 UTC
